export const wallets = {
	title: "Wallets",
	details: "",
	items: [
		{
			id: 1,
			title: "Keplr Wallet",
			device: ["IOS", "Android", "Desktop"],
			image: "what-is-tia/kepler-icon.jpg",
			backdropClass: "opacity-50",
			url: "https://www.keplr.app/",
			type: "external",
		},
		{
			id: 2,
			title: "Cosmostation",
			device: ["IOS", "Android", "Desktop"],
			image: "what-is-tia/cosmostation-icon.jpg",
			backdropClass: "opacity-100",
			url: "https://cosmostation.io/products/cosmostation_extension/",
			type: "external",
		},
		{
			id: 3,
			title: "Leap",
			device: ["IOS", "Android", "Desktop"],
			image: "what-is-tia/leap-icon.jpg",
			backdropClass: "opacity-100",
			url: "https://www.leapwallet.io/",
			type: "external",
		},
		{
			id: 4,
			title: "Ledger",
			device: ["IOS", "Android", "Desktop"],
			image: "what-is-tia/ledger-icon.jpg",
			backdropClass: "opacity-50",
			url: "https://www.ledger.com/",
			type: "external",
		},
	],
};
