export const ecosystemCategories = [
	{
		title: "Astria",
		category: ["Rollup","Rollups-as-a-service"],
		image: "ecosystem/astria.png",
		url: "https://astria.org/",
	},
	{
		title: "Alpha Dune",
		category: ["Rollup"],
		image: "ecosystem/alphadune.png",
		url: "https://alphadune.com/",
	},
	{
		title: "LightLink",
		category: ["Rollup"],
		image: "ecosystem/lightlink.png",
		url: "https://lightlink.io/",
	},
	{
		title: "Manta Network",
		category: ["Rollup"],
		image: "ecosystem/manta.png",
		url: "https://manta.network/",
	},
			{
				title: "AsMatch",
				category: ["Rollup"],
				image: "ecosystem/asmatch.png",
				url: "https://www.asmatch.app/",
			},
			{
				title: "Movement Labs",
				category: ["Rollup"],
				image: "ecosystem/movement.png",
				url: "https://movementlabs.xyz/",
			},
			{
				title: "Ojo",
				category: ["Rollup"],
				image: "ecosystem/ojo.png",
				url: "https://ojo.network/",
			},
			{
				title: "Deri",
				category: ["Rollup"],
				image: "ecosystem/deri.png",
				url: "https://deri.io/#/index",
			},
			{
				title: "Paima Studios",
				category: ["Rollup"],
				image: "ecosystem/paima.png",
				url: "https://paimastudios.com/",
			},
			{
				title: "Curio",
				category: ["Rollup"],
				image: "ecosystem/curio.png",
				url: "https://www.curio.gg/",
			},
			{
				title: "Pocket Network",
				category: ["Rollup"],
				image: "ecosystem/pocket.png",
				url: "https://www.pokt.network/",
			},
			{
				title: "Shogun",
				category: ["Rollup"],
				image: "ecosystem/shogun.png",
				url: "https://twitter.com/shogunfi/",
			},
			{
				title: "Eclipse",
				category: ["Rollup"],
				image: "ecosystem/eclipse.png",
				url: "https://www.eclipse.builders/",
			},
			{
				title: "Syndr",
				category: ["Rollup"],
				image: "ecosystem/syndr.png",
				url: "https://www.syndr.com/",
			},
			{
				title: "Hokum",
				category: ["Rollup"],
				image: "ecosystem/hokum.png",
				url: "https://hokum.gg/",
			},
			{
				title: "UniDex",
				category: ["Rollup"],
				image: "ecosystem/unidex.png",
				url: "https://www.unidex.exchange/",
			},
			{
				title: "Kinto",
				category: ["Rollup"],
				image: "ecosystem/kinto.png",
				url: "https://kinto.xyz/",
			},
			{
				title: "Waev",
				category: ["Rollup"],
				image: "ecosystem/waev.png",
				url: "https://www.waev.com/",
			},
			{
				title: "Zeko",
				category: ["Rollup"],
				image: "ecosystem/zeko.png",
				url: "https://zeko.io/",
			},
			{
				title: "ZKFair",
				category: ["Rollup"],
				image: "ecosystem/zkfair.png",
				url: "https://zkfair.io/",
			},
			{
				title: "Last L2",
				category: ["Rollup"],
				image: "ecosystem/lastl2.png",
				url: "https://golast.xyz/",
			},
			{
				title: "Dark Frontier",
				category: ["Rollup"],
				image: "ecosystem/darkfrontier.png",
				url: "https://darkfrontier.gg/",
			},
			{
				title: "Forma",
				category: ["Rollup"],
				image: "ecosystem/forma.png",
				url: "",
			},
			{
				title: "Caldera",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/caldera.png",
				url: "https://www.caldera.xyz/",
			},
			{
				title: "Vistara",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/vistara.png",
				url: "https://docs.vistara.dev/",
			},
			{
				title: "Snapchain",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/snapchain.png",
				url: "https://www.snapchain.dev/",
			},
			{
				title: "Altlayer",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/altlayer.png",
				url: "https://www.altlayer.io/",
			},
			{
				title: "Conduit",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/conduit.png",
				url: "https://conduit.xyz/",
			},
			{
				title: "Gateway",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/gateway.png",
				url: "https://gateway.fm/",
			},
			{
				title: "Gelato",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/gelato.png",
				url: "https://www.gelato.network/",
			},
			{
				title: "Lumoz",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/lumoz.png",
				url: "https://lumoz.org/",
			},
			{
				title: "Zeeve",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/zeeve.png",
				url: "https://www.zeeve.io/",
			},
			{
				title: "Karnot",
				category: ["Rollups-as-a-service"],
				image: "ecosystem/karnot.png",
				url: "https://www.karnot.xyz/",
			},
];
