export const pressData = {
	title: "Press & Media",
	text: "Build games with new capabilities. Celestia scales with the number of users so games can scale with their usebase.",
	items: [
        {
			id: 1,
			title: "Branding & Logos",
			text: "Learn about the token powering Celestia",
			image: "press/branding.png",
			type: "internal",
			figma: true,
			color: "#F3ECFF",
			url: "/press",
		},
        {
			id: 2,
			title: "Media Kit",
			text: "Explore the ecosystem of applications using Celestia",
			image: "press/media-kit.png",
			type: "internal",
			figma: true,
			color: "#FFF2E1",
			url: "/press",
		},
        {
			id: 3,
			title: "News",
			text: "Learn about the token powering Celestia",
			image: "press/news.png",
			type: "internal",
			figma: false,
			color: "#DEF7FF",
			url: "/press",
		},
        {
			id: 4,
			title: "Social",
			text: "Explore the ecosystem of applications using Celestia",
			image: "press/social.png",
			type: "internal",
			figma: false,
			color: "#E7FFD4",
			url: "/press",
		},
		{
			id: 5,
			title: "Enquiries",
			text: "Learn about the token powering Celestia",
			image: "press/enquiries.png",
			type: "internal",
			figma: false,
			color: "#F7F7F7",
			url: "/press",
		},
	],
};
