export const rollups = {
	title: "Rollups-as-a-Service",
	subtitle: "",
	description: "Deploy end-to-end on managed infrastructure using a Rollup-as-a-Service provider.",
	items: [
		{
			id: 1,
			title: "AltLayer",
			category: ["All", "Arbitrum ORBIT", "OP Stack", "Polygon CDK"],
			text: "We offer a versatile rollup stack including Arbitrum Orbit, OP stack, Polygon zkEVM and StarkWare.",
			image: "developer-portal/altlayer.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://altlayer.io/raas/",
			},
		},
		{
			id: 2,
			title: "Caldera",
			category: ["All", "Arbitrum ORBIT", "OP Stack"],
			text: "Caldera makes it easy to launch performant, customizable Arbitrum Orbit and OP Stack rollups. No code required.",
			image: "developer-portal/caldera.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://www.caldera.xyz/",
			},
		},
		{
			id: 3,
			title: "Conduit",
			category: ["All", "Arbitrum ORBIT", "OP Stack"],
			text: "Deploy a rollup in a few clicks, no code required. Fully-managed, production grade OP Stack and Arbitrum Orbit rollups on Ethereum.",
			image: "developer-portal/conduit.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://conduit.xyz/",
			},
		},
		{
			id: 4,
			title: "Gelato",
			category: ["All", "Arbitrum ORBIT", "OP Stack", "Polygon CDK"],
			text: "Deploy custom chains with cutting-edge web2 UX. Seamless integrations with all your favorite web3 tools and services.",
			image: "developer-portal/gelato.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://www.gelato.network/",
			},
		},
		{
			id: 5,
			title: "Zeeve",
			category: ["All", "Arbitrum ORBIT", "OP Stack", "Polygon CDK"],
			text: "Build, Customize, and Launch your production-grade Rollups with Zeeve’s Rollups as a Service (RaaS).",
			image: "developer-portal/zeeve.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://www.zeeve.io/",
			},
		},
		{
			id: 6,
			title: "Gateway",
			category: ["All", "Polygon CDK"],
			text: "Create your own zkEVM with all the infrastructure you need.",
			image: "developer-portal/gateway.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://gateway.fm/",
			},
		},
		{
			id: 7,
			title: "Lumoz",
			category: ["All", "Polygon CDK"],
			text: "A decentralized ZK-RaaS network featuring ZKP mining.",
			image: "developer-portal/lumoz.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://lumoz.org/",
			},
		},
		{
			id: 8,
			title: "Snapchain",
			category: ["All", "Polygon CDK"],
			text: "Leverage the power of ZK Rollups to scale your on-chain game or DeFi app cheaply and securely, without compromise.",
			image: "developer-portal/snapchain.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "https://snapchain.dev/",
			},
		},
		{
			id: 8,
			title: "Only All Box 1",
			category: ["All"],
			text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac ante non metus facilisis.",
			image: "developer-portal/placeholder-img.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "/",
			},
		},
		{
			id: 8,
			title: "Only All Box 2",
			category: ["All"],
			text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac ante non metus facilisis.",
			image: "developer-portal/placeholder-img.png",
			type: "external",
			link: {
				text: "Book demo",
				url: "/",
			},
		},
	],
};
